openapi: 3.0.0
info:
  title: SPD-Realisasi
  version: 1.0.0
servers:
  - url: http://localhost:9999
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
security:
  - basicAuth: []
paths:
  /api/spdrealisasi/bulk:
    post:
      tags:
        - General
      summary: apiPortalFZ (SPD-Realisasi)
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                - n_spd_id: "5"
                  n_realisasi_uangsaku: "50000"
                  c_realisasi_uangsaku_ket: test
                  n_realisasi_biayapenginapan: "50000"
                  c_realisasi_biayapenginapan_ket: test
                  n_realisasi_biayatransport: "50000"
                  c_realisasi_biayatransport_ket: test
                  n_realisasi_biayalain: "50000"
                  c_realisasi_biayalain_ket: test
                  d_realisasi_tanggal: "2023-06-06"
                  n_realisasi_subtotal: "500000"
                - n_spd_id: "5"
                  n_realisasi_uangsaku: "50000"
                  c_realisasi_uangsaku_ket: test
                  n_realisasi_biayapenginapan: "50000"
                  c_realisasi_biayapenginapan_ket: test
                  n_realisasi_biayatransport: "50000"
                  c_realisasi_biayatransport_ket: test
                  n_realisasi_biayalain: "50000"
                  c_realisasi_biayalain_ket: test
                  d_realisasi_tanggal: "2023-06-06"
                  n_realisasi_subtotal: "500000"
      security:
        - basicAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /api/spdrealisasi:
    post:
      tags:
        - General
      summary: apiPortalFZ (SPD-Realisasi) Bulk
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                n_spd_id: "5"
                n_realisasi_uangsaku: "50000"
                c_realisasi_uangsaku_ket: test
                n_realisasi_biayapenginapan: "50000"
                c_realisasi_biayapenginapan_ket: test
                n_realisasi_biayatransport: "50000"
                c_realisasi_biayatransport_ket: test
                n_realisasi_biayalain: "50000"
                c_realisasi_biayalain_ket: test
                d_realisasi_tanggal: "2023-06-06"
                n_realisasi_subtotal: "500000"
      security:
        - basicAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /api/spdrealisasi/1:
    put:
      tags:
        - General
      summary: apiPortalFZ (SPD-Realisasi)
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                n_spd_id: 38
                d_realisasi_tanggal: "2023-01-01"
                n_realisasi_uangsaku: 20000
                n_realisasi_biayapenginapan: 200000
                n_realisasi_biayatransportasi: 200000
                n_realisasi_biayalain: 20000
                n_realisasi_totalbiaya: 200000
                n_realisasi_hrd_uangsaku: 200000
                n_realisasi_hrd_biayapenginapan: 2000000
                n_realisasi_hrd_biayatransportasi: 20000
                n_realisasi_hrd_biayalain: 200000
                n_realisasi_hrd_totalbiaya: 20000
      security:
        - basicAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    delete:
        tags:
          - General
        summary: apiPortalFZ (SPD-Realisasi)
        security:
          - basicAuth: []
        responses:
          "200":
            description: Successful response
            content:
              application/json: {}
    get:
      tags:
        - General
      summary: apiPortalFZ (SPD-Realisasi) ById
      security:
        - basicAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /api/spdrealisasi/:
    get:
      tags:
        - General
      summary: apiPortalFZ (SPD-Realisasi) BySpdId
      security:
        - basicAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
